import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const avanttHeavy = localFont({
  src: "../public/fonts/Avantt-Heavy.otf",
  variable: "--font-avantt-heavy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl-NL">
      <head>
        {/* prefetch aws images  */}
        <link
          rel="preload"
          href="https://gianluca-vetrugno.s3.eu-west-3.amazonaws.com/gianluca-vetrugno.webp"
          as="image"
        />
        <link
          rel="dns-prefetch"
          href="https://gianluca-vetrugno.s3.eu-west-3.amazonaws.com"
        />
        <link
          rel="preconnect"
          href="https://gianluca-vetrugno.s3.eu-west-3.amazonaws.com"
          crossOrigin=""
        />
      </head>
      <body className={`${avanttHeavy.variable} antialiased bg-black`}>
        {children}
      </body>
    </html>
  );
}
